version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    restart: always
    expose:
      - 5432
    env_file:
      - .env


  web:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/fastapi_app
      - static_vol:/fastapi_app/static
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/fastapi_app
      - static_vol:/fastapi_app/static
    ports:
      - "80:80"
      - "443:443"
volumes:
  static_vol:
  media_vol: